SELECT COUNT(T.convenio_banco_id),
T.metodo_pago,
C.BANCO,
CL.NOMBRE||' '||CL.APELLIDO
FROM TRANSACCION_PAGO T
INNER JOIN CONVENIO_BANCO C ON C.CONVENIO_BANCO_ID = T.CONVENIO_BANCO_ID
INNER JOIN RESERVA_TEMPORAL R ON R.RESERVA_ID = T.RESERVA_ID
INNER JOIN CLIENTE CL ON CL.CLIENTE_ID = R.CLIENTE_ID
GROUP BY T.metodo_pago, C.BANCO, CL.NOMBRE, CL.APELLIDO
;



DECLARE
CURSOR C_CURSOR IS SELECT COUNT(T.convenio_banco_id),
T.metodo_pago,
C.BANCO,
CL.NOMBRE||' '||CL.APELLIDO
FROM TRANSACCION_PAGO T
INNER JOIN CONVENIO_BANCO C ON C.CONVENIO_BANCO_ID = T.CONVENIO_BANCO_ID
INNER JOIN RESERVA_TEMPORAL R ON R.RESERVA_ID = T.RESERVA_ID
INNER JOIN CLIENTE CL ON CL.CLIENTE_ID = R.CLIENTE_ID
GROUP BY T.metodo_pago, C.BANCO, CL.NOMBRE, CL.APELLIDO
;

BEGIN
null;
END;

